# Site settings
baseurl = "https://www.faultycat.com.au"
languageCode = "en-us"
title = "Faulty Cat Productions"
theme = "hugo-artists-theme"

[params]
<<<<<<< HEAD
    description = "Exploratory music and sound for games, new media, and interactive experiences."
    favicon = "favicon.ico"
    logo = ""

[params.postcss]
    postcss = false

[params.palette]
    text = "#666699"
    background = "#FFBF00"
    accent = "#ffeb99"
    foreground = "#666699"
    separator = "#6272a4"
    cyan = "#8be9fd"
    green = "#50fa7b"
    orange = "#ffb86c"
    pink = "#ff79c6"
    purple = "#bd93f9"
    red = "#ff5555"
    yellow = "#f1fa8c"

[params.fontsizes]
    base = "1em"
    p = "1.25em"
    h4 = "1.563em"
    h3 = "1.953em"
    h2 = "2.441em"
    h1 = "3.052em"

[params.googlefonts]
    font = "Inconsolata"

[params.serviceWorker]
    enable = false

[params.header]
    show = false

[params.cta]
    show = false
    message = "Learn more!"
    link = "https://github.com/danielkvist/hugo-piercer-theme#readme"

[params.fa]
    disable = false
    kit = ""

[params.form]
    show = false
    netlify = false
    action = ""
    method = "POST"
    section = "Contact me!"
    disclaimer = "Elit anim sit labore tempor exercitation in ad cupidatat."
    inputNameName = "Name"
    inputNameLabel = "Name"
    inputNamePlaceholder = "Your Name"
    inputEmailName = "Email"
    inputEmailLabel = "Email"
    inputEmailPlaceholder = "Your Email"
    SubmitValue = ""

[params.contact]
    show = true
    email = "vincent.giles@me.com"
    # phone = ""
    skype = "live:vincent.giles_1"
    address = "Melbourne, VIC, AU"

[params.date]
    format = ""

[params.social]
    twitter = "@VincentGiles"
    # facebook = "#"
    # github = "#"
    # gitlab = "#"
    # codepen = "#"
    # instagram = "#"
    # pinterest = "#"
    # youtube = "#"
    # linkedin = ""
    # weibo = ""
    # mastodon = ""
    # tumblr = ""
    # flickr = ""
    # "500px" = ""
    # rss = "#"

[params.copy]
    message = "Copyright 2019 Faulty Cat"

[params.agreement]
    message = "Faulty Cat uses <a href=\"#\" alt=\"font awesome\">Font Awesome</a>."

[params.notfound]
    message = "Oh no. :("
=======

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Vincent Giles"
	description = "Exploratory composer and producer of music and sound for games, new media, and interactive experiences"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "vincent.giles@me.com"


	# Header an navigation
	#
	# To change the header background the 'hero-bg-jpg' at 'static/img'.
	# Do the same with the logo ('logo.svg').
	# But keep the original filename!
	[params.header]
		title = "Faulty Cat Productions"
		shortBio = "Exploratory music for games, new media, and interactive experiences"


	# About section
	#
	# Replace the 'avatar.jpg' under 'static/img' with your own image.
	[params.about]
		title = "Vincent Giles"
		bio = "_Website currently under development._<br />Vincent Giles is a composer and producer of exploratory music. He discovers new ways to do creative things for human experiences."

		# [[params.about.skills]]
		# 	name = "Communication"
		# 	value = 9

		# [[params.about.skills]]
		# 	name = "Organization"
		# 	value = 7

		# [[params.about.skills]]
		# 	name = "Learning"
		# 	value = 10

		# [[params.about.skills]]
		# 	name = "Teaching"
		# 	value = 6

		# [[params.about.skills]]
		# 	name = "Planning"
		# 	value = 7

		# [[params.about.skills]]
		# 	name = "Visual Design"
		# 	value = 5

		# [[params.about.skills]]
		# 	name = "UX Design"
		# 	value = 8

		# [[params.about.skills]]
		# 	name = "Programming"
		# 	value = 6

	# Contact secion
	[params.contact]
		title = "Contact"

		# The following social network icons are available:
		# 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin'
		# 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
		[[params.contact.social]]
			icon = "twitter"
			link = "//twitter.com/VincentGiles"

		# [[params.contact.social]]
		# 	icon = "dribbble"
		# 	link = "//dribbble.com/travisneilson"

		# [[params.contact.social]]
		# 	icon = "behance"
		# 	link = "//www.behance.net/travisneilson"

		[[params.contact.social]]
			icon = "youtube"
			link = "//www.youtube.com/composervince"

		# [[params.contact.social]]
		# 	icon = "linkedin"
		# 	link = "//www.linkedin.com/in/travisneilson"


	[params.form]
		title = "Let's make something together"
		# Form fields
		name = "Your Name"
		email = "Your Email"
		message = "Tell me about your project"
		buttonText = "Send"


	[params.footer]
		copyright = "Content Copyright 2019 Faulty Cat Productions except where noted. Designt published under the Unlicense License."
>>>>>>> development
