# Site settings
baseurl = "https://www.faultycat.com.au/"
languageCode = "en-us"
title = "Faulty Cat Productions"
theme = "vg-theme"

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
#   [[module.mounts]]
#     source = "static"
#     target = "static"

[params]

	name = "Faulty Cat Productions || Vincent Giles"
	description = "Melbourne, Victoria. Exploratory music composition, producuction, sound design, and project management, for games, film, new media, installation, and interactivity."

	email = "hi@faultycat.com.au"


	[params.header]
		title = "Faulty Cat Productions"
		heading = "Vincent Giles"
		subHeading = "Uncompromising sound and music for exploratory art projects"
		webTag = "Values-driven sonic innovation, together."
		logo = "../img/logo.svg"

	[params.about]
		title = "Hello!"
		bio = "I'm **Vincent**, a **composer, sound designer, and producer**"
		image = "img/giles_promo.jpg"
		image_width = "300px"
		blurb = """
Artists, makers, and curators often want **boundary-pushing** sound but hit technical walls or mismatched creative priorities. I help amplify their ideas – whether for **concert halls**, **site-specific installations**, or **games and visual media** – through systems-first design and feedback-driven iteration. Let's turn your concept into something **uncompromising** and quietly transformative.
"""
		blurb_style = "border-right: 3px solid #b89c66; padding-right: 1.5rem;" # Custom CSS
		more_link = "/about"  # URL for the page
		more_text = "Read my full story →"  # Link text
		more_style = "display: inline-block; margin-top: 1rem; color: #b89c66;"  # Optional	

	[params.about-full]
		title = "About"
		bio = '''
I partner with artists, councils, and galleries to create sound that reveals new layers in its medium—whether for concert halls, games, installations, or public spaces. Sometimes, projects can falter or lack clarity from technical hurdles or mismatched visions, wasting chances to connect deeply with new and existing audiences.

With 20 years of experience in exploratory sound practice—from composing concert works (published by Wirripang, Edition Resonance, and Move Records) to producing ambisonic public art and directing Tilde New Music & Sound Art—I ensure your project thrives through:

- End-to-end vision: Guiding from concept to post-production, with technical rigour meeting creative ambition.
- Site-specific innovation: Transforming spaces (physical/virtual) through acoustic intelligence and conceptual rigour.
- Permaculture-driven process: Systems-first design, iterative feedback, resilience over waste.

Let’s turn your idea into a quietly transformative experience that is creatively uncompromising.
'''
		face_img = "img/giles_promo.jpg"
		# "Vincent Giles of Faulty Cat Productions is a composer and producer creating exploratory music and sound for interactive and immersive experiences. "

		# [[params.about.skills]]
		# 	name = "Composition"
		# 	value = 9

		# [[params.about.skills]]
		# 	name = "Sound Design"
		# 	value = 8

		# [[params.about.skills]]
		# 	name = "Production"
		# 	value = 9

		# [[params.about.skills]]
		# 	name = "Project Management"
		# 	value = 8

		# [[params.about.skills]]
		# 	name = "Empathy"
		# 	value = 9

		# [[params.about.skills]]
		# 	name = "Communication"
		# 	value = 8

		# [[params.about.skills]]
		# 	name = "Grant-Writing"
		# 	value = 7

		# [[params.about.skills]]
		# 	name = "New Media Technologies"
		# 	value = 7

	# # Podcast
	# [params.podcast]
	# 	title = "Filtered Noise"
	# 	bio = ""

	# Contact secion
	[params.contact]
		title = "Connect"

		[[params.contact.social]]
			icon = "instagram"
			link = "//instagram.com/composervince"

		[[params.contact.social]]
			icon = "soundcloud"
			link = "//www.soundcloud.com/vince-giles"

	[params.form]
		title = "Let's make something together"
		# Form fields
		name = "Your Name"
		email = "Your Email"
		message = "Tell me about your project"
		buttonText = "Send"


	[params.footer]
		copyright = '''
I live and work on unceded Wurundjeri Country in Naarm (Melbourne).

As an uninvited guest, I acknowledge the great and ongoing loss of people and knowledge caused by the European colonial project(s).

This website is built using free and open source software and hosted in a cloud-based system that reduces environmental impact by serving content on-demand.

As such, users may rarely encounter up to a one-minute delay in access as the servers dynamically power-up for service.
'''


# {{ < soundcloud 1383778492 >