baseurl = "/"
title = "Faulty Cat Productions"
author = "Vincent Giles"
googleAnalytics = ""
enableRobotsTXT = true
defaultContentLanguage = "en"
language = "en-US"
paginate = 3
staticDir = ["static"]

theme = "piercer"
themesDir = "./themes"

[privacy]
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = true
        respectDoNotTrack = true
        useSessionStorage = false
    [privacy.instagram]
        disable = true
        simple = false
    [privacy.twitter]
        disable = false
        enableDNT = true
        simple = false
    [privacy.vimeo]
        disable = true
        simple = false
    [privacy.youtube]
        disable = true
        privacyEnhanced = true

[params]
    description = "Exploratory music and sound for games, new media, and interactive experiences."
    favicon = "favicon.ico"
    logo = ""

[params.postcss]
    postcss = false

[params.palette]
    text = "#666699"
    background = "#FFBF00"
    accent = "#e6b800"
    foreground = "#666699"
    separator = "#6272a4"
    cyan = "#8be9fd"
    green = "#50fa7b"
    orange = "#ffb86c"
    pink = "#ff79c6"
    purple = "#bd93f9"
    red = "#ff5555"
    yellow = "#f1fa8c"

[params.fontsizes]
    base = "1em"
    p = "1.25em"
    h4 = "1.563em"
    h3 = "1.953em"
    h2 = "2.441em"
    h1 = "3.052em"

[params.googlefonts]
    font = "Open Sans"

[params.serviceWorker]
    enable = true

[params.header]
    show = false

[params.cta]
    show = false
    message = "Learn more!"
    link = "https://github.com/danielkvist/hugo-piercer-theme#readme"

[params.fa]
    disable = false
    kit = ""

[params.form]
    show = false
    netlify = false
    action = ""
    method = "POST"
    section = "Contact me!"
    disclaimer = "Elit anim sit labore tempor exercitation in ad cupidatat."
    inputNameName = "Name"
    inputNameLabel = "Name"
    inputNamePlaceholder = "Your Name"
    inputEmailName = "Email"
    inputEmailLabel = "Email"
    inputEmailPlaceholder = "Your Email"
    SubmitValue = ""

[params.contact]
    show = true
    email = "vincent.giles@me.com"
    # phone = ""
    skype = "live:vincent.giles_1"
    address = "Melbourne, VIC, AU"

[params.date]
    format = ""

[params.social]
    twitter = "@VincentGiles"
    # facebook = "#"
    # github = "#"
    # gitlab = "#"
    # codepen = "#"
    # instagram = "#"
    # pinterest = "#"
    # youtube = "#"
    # linkedin = ""
    # weibo = ""
    # mastodon = ""
    # tumblr = ""
    # flickr = ""
    # "500px" = ""
    # rss = "#"

[params.copy]
    message = "Copyright 2019 Faulty Cat"

[params.agreement]
    message = "Faulty Cat uses <a href=\"#\" alt=\"font awesome\">Font Awesome</a>."

[params.notfound]
    message = "Oh no. :("