#base settings
baseURL = "https://www.faultycat.com.au/"
languageCode = "en-us"

# Navigation links (now uses Hugo's pages)

[[params.header.nav]]
    name = "Home"
    url = "/"

[[params.header.nav]]
    name = "About"
    url = "/about"  # Links to content/work/_index.md

[[params.header.nav]]
    name = "Music/Sound"
    url = "/composition"

[[params.header.nav]]
    name = "Mentoring/Education"
    url = "/workshops"

[[params.header.nav]]
    name = "Post-Production"
    url = "/post-prod"

# [[params.header.nav]]
#     name = "Portfolio"
#     url = "/portfolio"

[[params.header.nav]]
    name = "Publishing"
    url = "https://www.edition-resonance.xyz"

[[params.header.nav]]
    name = "Blog"
    url = "https://www.fcpvg.work"

[[params.header.nav]]
    name = "Contact"
    url = "/#contact"


[module]
    [[module.mounts]]
        source = "assets"
        target = "assets"
    # [[module.mounts]]
    #     source = "static"
    #     target = "static"

[params]
    name = "Faulty Cat Productions || Vincent Giles"
    description = "Melbourne, Victoria. Exploratory music composition, producuction, sound design, and project management, for games, film, new media, installation, and interactivity."
    # email = "hi@faultycat.com.au"


    [params.header]
        title = "Faulty Cat Productions"
        heading = "Vincent Giles"
        subHeading = "Sound and music for exploratory art projects"
        webTag = "together we can build lasting sonic experiences"
        logo = "../logo.svg"

    [params.about]
        title = "Hello!"
        bio = "I'm **Vincent**, a biscuit-powerd **composer, sound designer, and producer**, and reformed bass player"
        image = "img/general/ec_portrait_2.png"
        image_width = "300px"
        blurb = """
Artists, makers, and curators often want **boundary-pushing sound and music** or have hit technical walls or mismatched creative priorities. I help amplify their ideas – whether for **concert halls**, **site-specific installations**, or **games and visual media** – through systems-first design and feedback-driven iteration. Let's turn your concept into something **uncompromising** and quietly transformative.
"""
        blurb_style = "border-right: 3px solid #b89c66; padding-right: 1.5rem;" # Custom CSS
        more_link = "/about"  # URL for the page
        more_text = "Read about my story so far →"  # Link text
        more_style = "display: inline-block; margin-top: 1rem; color:rgb(242, 246, 216);"  # Optional    

    [params.about-full]
        title = "About Vincent & Faulty Cat Productions"
        bio = '''
I partner with artists, councils, and galleries to create sound that reveals new layers in its medium—whether for concert halls, games, installations, or public spaces. Sometimes, projects can falter or lack clarity from technical hurdles or mismatched visions, wasting chances to connect deeply with new and existing audiences.

With 20 years of experience in exploratory sound practice—from composing concert works (published by Wirripang, Edition Resonance, and Move Records) to producing ambisonic public art and directing Tilde New Music & Sound Art—I ensure your project thrives through:

- End-to-end vision: Guiding from concept to post-production, with technical rigour meeting creative ambition.
- Site-specific innovation: Transforming spaces (physical/virtual) through acoustic intelligence and conceptual rigour.
- Permaculture-driven process: Systems-first design, iterative feedback, resilience over waste.

Let's turn your idea into a quietly transformative experience that is creatively uncompromising.
'''
        face_img = "img/giles_promo.jpg"

    [params.contact]
        title = "Connect with me"
        email = "hi@faultycat.com.au"
        instagram_user = "composervince"  # Without @
        instagram_count = 6            # Posts to show

        [[params.contact.social]]
            icon = "instagram"  # icon-key (see below)
            link = "https://instagram.com/composervince"
            name = "Instagram"  # For alt text

        [[params.contact.social]]
            icon = "bandcamp"
            link = "https://vincentgiles.bandcamp.com/"
            name = "Bandcamp"

        # Optional Instagram Feed

        [params.form]
            title = "Let's make something together"
            # Form fields
            name = "Your Name"
            email = "Your Email"
            message = "Tell me about your project"
            buttonText = "Connect"

    [params.footer]
        acknowledgement = """
I live and work on unceded **Wurundjeri Country** in **Naarm (Melbourne)**.

As an uninvited guest, I acknowledge the great and ongoing loss of people and knowledge caused by the European colonial project(s).
"""
		FOSS1 = "and hosted such that it reduces environmental impact by serving content on-demand."
		FOSS2 = "As such, users may rarely encounter up to a one-minute delay in access as the servers dynamically power-up for service. The theme is derived from the [hugo artists theme](https://github.com/digitalcraftsman/hugo-artists-theme) with very liberal modification."
		ABN = "ABN: 91 315 232 577"


    [params.services]
        title = "I want to build moving, challenging, and lasting sonic experiences"
        subtitle = "These are my offerings to the world"

        [[params.services.cards]]
            title = "Composition, Sound Design, and Production"
            image = "../img/services/composition.png"  # Path to image
            description = "I compose original music for instrumentalists and ensembles, games, films. I design sound for installation art, games, film (or suggest something!)"
            link = "/composition"
            link_text = "More information & portfolio →"

        [[params.services.cards]]
            title = "Workshops & Public Speaking" 
            image = "../img/services/workshop.png"
            description = "I offer workshops, mentoring, and public engagement such as speaking panels on public art, sound art, contemporary music."
            link = "/workshops"
            link_text = "See examples →"

        [[params.services.cards]]
            title = "Audio Editing & Post Production"
            image = "../img/services/consulting.jpg"
            description = "I offer audio editing (for example, for podcasts) and post-production, including mixing, along with general consulting services in this space." 
            link = "/post-prod"
            link_text = "Check it out →"

    [params.showreel]
        title = "Showreel"
        subtitle = "Sound and music for exploratory projects."

        # Choose ONE of these:
        vimeo_id = ""  # Just the ID from Vimeo URL
        youtube_id = "" # Just the ID from YouTube URL
        # OR for custom embed:
        custom_embed = '''
<iframe title="vimeo-player" src="https://player.vimeo.com/video/950659108?h=33c18b5d7b" width="640" height="360" frameborder="0" allowfullscreen></iframe>
'''
        # SoundCloud section
        soundcloud_playlist = "1383778492"  # Playlist ID from URL
        soundcloud_color = "e0982c"         # Matches your accent color

[outputs]
    home = ["HTML", "RSS"]
    page = ["HTML"]  # Force only HTML for pages
    section = ["HTML"] # Disable XML for sections
    taxonomy = ["HTML"]
    term = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.link]
        enableDefault = true
    [markup.goldmark.renderer]
        unsafe = true
        hardWraps = false

[params.testimonials]
  title = "Testimonials & Reviews"
  subtitle = "What people think of my work."

[markup.goldmark.parser]
    wrapStandAloneImageWithinParagraph = false