# Site settings
baseurl = "https://www.faultycat.com.au/"
languageCode = "en-us"
title = "Faulty Cat Productions"
theme = "hugo-artists-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Faulty Cat Productions: About"
	description = "Exploratory music composer, producer, sound designer, for games, film, new media, installation, and interactivity."

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "faultycatproductions@gmail.com"


	# Header an navigation
	#
	# To change the header background the 'hero-bg-jpg' at 'static/img'.
	# Do the same with the logo ('logo.svg').
	# But keep the original filename!
	[params.header]
		title = "Faulty Cat Productions"
		shortBio = "Exploratory music and sound design for games, new media, and interactive experiences"


	# About section
	#
	# Replace the 'avatar.jpg' under 'static/img' with your own image.
	[params.about]
		title = "About Faulty Cat Productions"
		bio = "**Vincent Giles** is a [composer](https://www.vgiles.net), sound designer, and [producer](https://www.tilde.net.au) of exploratory music. **Faulty Cat Productions** is a way of discovering new ways to do creative things for human experiences."

		[[params.about.skills]]
			name = "Composition"
			value = 9

		[[params.about.skills]]
			name = "Sound Design"
			value = 8

		[[params.about.skills]]
			name = "Empathy"
			value = 9

		[[params.about.skills]]
			name = "Production"
			value = 9

		[[params.about.skills]]
			name = "Communication"
			value = 8

		[[params.about.skills]]
			name = "Project Management"
			value = 8

		[[params.about.skills]]
			name = "Grant Writing"
			value = 6

		[[params.about.skills]]
			name = "Curation"
			value = 6

	# # Podcast
	# [params.podcast]
	# 	title = "Filtered Noise"
	# 	bio = ""

	# Contact secion
	[params.contact]
		title = "Connect"

		# The following social network icons are available:
		# 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin'
		# 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
		[[params.contact.social]]
			icon = "twitter"
			link = "//twitter.com/VincentGiles"

		[[params.contact.social]]
			icon = "instagram"
			link = "//instagram.com/composervince"

		[[params.contact.social]]
			icon = "soundcloud"
			link = "//www.soundcloud.com/vince-giles"

		[[params.contact.social]]
			icon = "youtube"
			link = "//www.youtube.com/composervince"

		# [[params.contact.social]]
		# 	icon = "linkedin"
		# 	link = "//www.linkedin.com/in/travisneilson"


	[params.form]
		title = "Let's make something together"
		# Form fields
		name = "Your Name"
		email = "Your Email"
		message = "Tell me about your project"
		buttonText = "Send"


	[params.footer]
		copyright = "Content Copyright 2020 Faulty Cat Productions except where noted. Design published under the Unlicense License. Portrait by Emily Churchill."
