# Navigation links (now uses Hugo's pages)
[[params.header.nav]]
    name = "About"
    url = "/about"  # Links to content/work/_index.md

[[params.header.nav]]
    name = "Portfolio"
    url = "/about" # Links to content/about.md

[[params.header.nav]]
    name = "Publishing"
    url = "https://www.edition-resonance.xyz"

[[params.header.nav]]
    name = "Blog"
    url = "https://www.fcpvg.work"

[[params.header.nav]]
    name = "Contact"
    url = "/contact"

[module]
    [[module.mounts]]
        source = "assets"
        target = "assets"
    # [[module.mounts]]
    #     source = "static"
    #     target = "static"

[params]
    name = "Faulty Cat Productions || Vincent Giles"
    description = "Melbourne, Victoria. Exploratory music composition, producuction, sound design, and project management, for games, film, new media, installation, and interactivity."
    # email = "hi@faultycat.com.au"

    [params.header]
        title = "Faulty Cat Productions"
        heading = "Vincent Giles"
        subHeading = "Uncompromising sound and music for exploratory art projects"
        webTag = "Values-driven sonic innovation, together."
        logo = "../logo.svg"

    [params.about]
        title = "Hello!"
        bio = "I'm **Vincent**, a **composer, sound designer, and producer**"
        image = "img/giles_promo.jpg"
        image_width = "300px"
        blurb = """
Artists, makers, and curators often want **boundary-pushing** sound but hit technical walls or mismatched creative priorities. I help amplify their ideas – whether for **concert halls**, **site-specific installations**, or **games and visual media** – through systems-first design and feedback-driven iteration. Let's turn your concept into something **uncompromising** and quietly transformative.
"""
        blurb_style = "border-right: 3px solid #b89c66; padding-right: 1.5rem;" # Custom CSS
        more_link = "/about"  # URL for the page
        more_text = "Read more →"  # Link text
        more_style = "display: inline-block; margin-top: 1rem; color: #b89c66;"  # Optional    

    [params.about-full]
        title = "About Vincent & Faulty Cat Productions"
        bio = '''
I partner with artists, councils, and galleries to create sound that reveals new layers in its medium—whether for concert halls, games, installations, or public spaces. Sometimes, projects can falter or lack clarity from technical hurdles or mismatched visions, wasting chances to connect deeply with new and existing audiences.

With 20 years of experience in exploratory sound practice—from composing concert works (published by Wirripang, Edition Resonance, and Move Records) to producing ambisonic public art and directing Tilde New Music & Sound Art—I ensure your project thrives through:

- End-to-end vision: Guiding from concept to post-production, with technical rigour meeting creative ambition.
- Site-specific innovation: Transforming spaces (physical/virtual) through acoustic intelligence and conceptual rigour.
- Permaculture-driven process: Systems-first design, iterative feedback, resilience over waste.

Let's turn your idea into a quietly transformative experience that is creatively uncompromising.
'''
        face_img = "img/giles_promo.jpg"

    [params.contact]
        title = "Connect with me"
        email = "hi@faultycat.com.au"
        instagram_user = "composervince"  # Without @
        instagram_count = 6            # Posts to show

        [[params.contact.social]]
            icon = "instagram"  # icon-key (see below)
            link = "https://instagram.com/composervince"
            name = "Instagram"  # For alt text

        [[params.contact.social]]
            icon = "bandcamp"
            link = "https://vincentgiles.bandcamp.com/"
            name = "Bandcamp"

        # Optional Instagram Feed

        [params.form]
            title = "Let's make something together"
            # Form fields
            name = "Your Name"
            email = "Your Email"
            message = "Tell me about your project"
            buttonText = "Connect"

    [params.footer]
        copyright = '''
Copyright 2025 Faulty Cat Productions/Vincent Giles. All Rights Reserved.

I live and work on unceded Wurundjeri Country in Naarm (Melbourne).

As an uninvited guest, I acknowledge the great and ongoing loss of people and knowledge caused by the European colonial project(s).

This website is built using [free and open source software](https://gohugo.io) and hosted in a cloud-based system that reduces environmental impact by serving content on-demand. 
As such, users may rarely encounter up to a one-minute delay in access as the servers dynamically power-up for service. The theme is derived from the [hugo artists' theme](https://github.com/digitalcraftsman/hugo-artists-theme) with very liberal modification.

ABN: 91 315 232 577
'''

    [params.services]
        title = "What I offer"
        subtitle = "Values-driven sonic innovation, together."

        [[params.services.cards]]
            title = "Composition, Sound Design, and Production"
            image = "../img/services/composition.png"  # Path to image
            description = "I compose original music for instrumentalists and ensembles, games, films. I design sound for installation art, games, film (or suggest something!). I do audio production and post-production including editing and mixdown, and other by need/request."
            link = "/composition"
            link_text = "View portfolio →"

        [[params.services.cards]]
            title = "Workshops & Public Speaking" 
            image = "../img/services/workshop.png"
            description = "I offer workshops, mentoring, and public engagement such as speaking panels on public art, sound art, contemporary music."
            link = "/sound-design"
            link_text = "See examples →"

        [[params.services.cards]]
            title = "Consulting"
            image = "../img/services/consulting.jpg"
            description = "I offer consultation services relating to audio needs for your business." 
            link = "/consulting"
            link_text = "Get in touch →"

    [params.showreel]
        title = "Showreel"
        subtitle = "Uncompromising sound and music for exploratory projects."

        # Choose ONE of these:
        vimeo_id = ""  # Just the ID from Vimeo URL
        youtube_id = "" # Just the ID from YouTube URL
        # OR for custom embed:
        custom_embed = '''
<iframe title="vimeo-player" src="https://player.vimeo.com/video/950659108?h=33c18b5d7b" width="640" height="360" frameborder="0" allowfullscreen></iframe>
'''
        # SoundCloud section
        soundcloud_playlist = "1383778492"  # Playlist ID from URL
        soundcloud_color = "e0982c"         # Matches your accent color

[outputs]
    home = ["HTML", "RSS"]
    page = ["HTML"]  # Force only HTML for pages
    section = ["HTML"] # Disable XML for sections
    taxonomy = ["HTML"]
    term = ["HTML"]

[params.testimonials]
  title = "Testimonials"
  subtitle = "What people think of my work"